[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "foundry-devops/src/=lib/foundry-devops/src/"
]
# Required to executes bash scripts from within foundry
# Pay attention using it - Can be dangerous
ffi = true
fs_permissions = [
    { access = "read", path = "./broadcast" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
